version: '3'

services:
  server:
    image: server
    build:
      context: ./api_server
    restart: always
    depends_on:
      - mongo
      - broker
    environment:
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_SERVICE=mongo
      - BROKER_HOST=broker
    # limit logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    

  mongo:
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      # Set mondo db storage voulume name.
      - mongo-db:/data/db
    # limit logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  
  client:
    image: client-umi
    build: 
      context: ./my_umi_app
    restart: always
    # limit logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
  
  broker:
    image: broker
    build:
      context: ./broker
    restart: always
    # limit logs
    logging:
      options:
        max-size: "10m"
        max-file: "3"
volumes:
  mongo-db: